use_default_settings: true

general:
  instance_name: "jcXproxy SearXNG"
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "${SEARXNG_SECRET}"
  image_proxy: false
  limiter: true
  public_instance: false

ui:
  default_theme: simple
  static_use_hash: true

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20

engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: mojeek
    engine: mojeek
    shortcut: mj
    disabled: false
